---
title: "**Sobre el grupo**"
subtitle: " "
author: "dgonzalez"
date: ""
output:
  html_document:
    toc: no
    toc_depth: 2
    toc_float: yes
    code_folding: hide
    theme: flatly
    css: style.css
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment = NA)

# colores
c0= "#FFCC00"
c1= "#FFAD42"
c2= "#FF5A42"
c3= "#E1286F"
c4= "#4983F6"
c5= "#783AC7"
c6= "#2C5697" # AZZUL INSTITUCIONAL
c7= "#F7F7F7" # FONDO GRIS CLARO WEB

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Instalar y cargar las librerías necesarias
#install.packages("ggplot2")
library(ggplot2)

# Crear el data.frame
data <- data.frame(
  Nombre = c("Laura Marcela Bedoya Serna", "Camila Cardenas Rojas", "Isabella Castaño Florez", 
             "Cataño Rodriguez", "Chaguendo Mendoza", "Mariana Cortes Rengifo", "Nicolas Figueroa Eraso", 
             "Galeano Castañeda", "Juan Gonzalez Sanchez", "Angie Guzman Espinosa", "Mendoza Vargas", 
             "Isabela Muñoz Gonzalez", "Laura Valentina Murillo Gomez", "Natalia Parra Escandon", 
             "Preciado Portela", "Karla Quiñones Muñoz", "Juan Ramirez Landazabal", "Luna Rivera Muñoz", 
             "Juan Rojas Rosada", "Leonardo Jose Rojas Leon", "Juan Silva Sanchez", "Solarte Zambrano", 
             "Juan Trujillo Escobar", "Mariana Vanegas Acosta", "Manuel Vera Orozco", "Villamizar Tasama", 
             "Zambrano Vacca"),
  Emplid = c(8930684, 8969738, 8966599, 8981810, 8947277, 8980137, 8966335, 8972652, 8962427, 8984494, 
             8980883, 8972507, 8955842, 8970395, 8972189, 8975770, 8967644, 8977165, 8968923, 8984367, 
             8983324, 8984379, 8978688, 8978814, 8958413, 00008953948, 8987407),
  Carrera = c("Administración de Empresas", "Mercadeo", "Mercadeo", "Negocios Internacionales", "Turismo", 
              "Negocios Internacionales", "Administración de Empresas", "Mercadeo", "Mercadeo", 
              "Negocios Internacionales", "Negocios Internacionales", "Turismo", "Administración de Empresas", 
              "Mercadeo", "Mercadeo", "Negocios Internacionales", "Negocios Internacionales", 
              "Negocios Internacionales", "Turismo", "Administración de Empresas", 
              "Administración de Empresas Noc", "Administración de Empresas", "Negocios Internacionales", 
              "Negocios Internacionales", "Negocios Internacionales", "Negocios Internacionales", 
              "Negocios Internacionales"),
  Matriculada = c(5, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1),
  Cancelada = c(4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0),
  Perdida = c(0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  Promedio = c(0, 3.61, 4.43, 3.96, 3.78, 4.15, 3.55, 4.3, 3.45, 3.6, 3.96, 3.79, 3.6, 4.15, 3.97, 
               4, 4.04, 3.95, 4.09, 4.61, 3.73, 4.16, 3.78, 4.09, 3.69, 3.87, 4.31)
)


# Instalar los paquetes necesarios si no están ya instalados
if (!require(ggplot2)) install.packages("ggplot2")
if (!require(dplyr)) install.packages("dplyr")
if (!require(paletteer)) install.packages("paletteer")
library(paletteer)
library(ggplot2)
library(dplyr)



# pastel_colors <- paletteer_c("ggthemes::Orange-Blue-White Diverging",7)
pastel_colors <-c(c1,c2,c3,c4,c5) 

# Diagrama circular para la variable Carrera
carrera_counts <- data %>% 
  group_by(Carrera) %>% 
  summarise(count = n())

ggplot(carrera_counts, aes(x = "", y = count, fill = Carrera)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  theme_void() +
  scale_fill_manual(values = pastel_colors) +
  labs(title = "Distribución de Carrera")

# Diagrama de cajas para la variable Promedio
ggplot(data, aes(x = Carrera, y = Promedio, fill = Carrera)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_manual(values = pastel_colors) +
  labs(title = "Diagrama de Cajas para la Variable Promedio por Carrera")




```
